# "sudo" is needed just for Docker
sudo: required
language: python
python:
- 3.6.0
install:
- pip install -r requirements-freeze.txt
- npm install cypress --save-dev

# TODO: Is the Travis Node/NPM good enough?
#  - node --version
#  - NODE_VERSION=6.11.0
#  - nvm install $NODE_VERSION
#  - nvm use $NODE_VERSION
#  - node --version
#
#  - npm --version
#  - npm install -g npm@3.10.10
#  - npm --version

script:
- ./test.sh
after_success:
- source define_repo.sh
- tag_push() { echo "Tagging into $2"; sudo docker tag $1 $2; sudo docker push $2; }

- sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
# Always update "latest": the cache will be used for the next build.
- tag_push $IMAGE $REPO
- >
    if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
      echo "PR!";
      BRANCH=`echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | perl -pne 'chomp;s{.*/}{};s/\W/-/g'`;
      tag_push $IMAGE $REPO:$BRANCH;
      tag_push $IMAGE $REPO:latest-pr;
    fi
- >
    if [ ! -z "$TRAVIS_TAG" ]; then
      echo "Git tag!";
      tag_push $IMAGE $REPO:$TRAVIS_TAG;
      tag_push $IMAGE $REPO:latest;
    fi
env:
  global:
    - secure: "JfRF9G/Q6K3JG9J4Tbl17tg5Pv2xpdI/WxmPEmsIoGqmrbYbhiheS2H/xJ7gYF3PiRsVZn0TjShoCUEikSX3L77u7PoiP0QgY2MHzFhx5+loe/0hhhRyDqEP0Nc24N36zGH5tdhjCzuEjNyavl9+nyV+PxzeaczGSa5SwW6D5cfIlt9554vRyNn3tqQpQiH9pA1/sDE3/0tCkVhjeACa73aYtAxbkuioBabxrw0Cf4/mGDbjG9M9Ial5ThN0+g02inJKec9Q23m7OzKN6LY/ExJdWm1BIv0qyAeQgODuH2QPJFmQgaYT6xwzvYibjFE1PADVgQJBUAWecSmdBInosSfxBPWG2V5wYZlEm2QZlhWvs3qDnKigSMoMv3JWdB1a9SImG4/18T/RFcyB399gTxEBeJQlrRS8hxOzjz8/8C5eftb2liRc88WZG0j/W3UaWFf+8lnxU+siz0gkyjDrPc2R6CwoOphVJpcF15ezXwvcCr2bNe5J3PHNaf5drb+zBdLLIsZ0ncxs3jQGkwmI5VbAv4o8SR30wumDdcGm4jbLkZW8AKPTz3ikF3WhOUdQXd00prFUBio34WH6E0tNcRlGEa9tP+jpKfRf+vevcNHwtRN97x3g6PhY5WNTUU8LGINQQkAGEKPbPa5/Fkcz0ioOnjMwWHqP5bsGTvQyAOc="
    - secure: "dJDUNQTk0rVOconzCHBfzFPg4UbdyMBfAo2KyBGxQ6tgADztOYAgtvJPuy3YECdGcXMBjibcyvCjwfYn3pPFOgD/adJdDIwvGHDs8l0NMRdqL7vLMHdwZQ1xHjNOg2P7d0+LRCh6ouauKTel+1+ZQxHsNUyYkQ9zBVZCDS1+4Qcxgm9YlYgFqKGZVunH5orkeyp83hGLxqAxzNDm2wR/UU6Gaf87DypcvKFxGW7X2j6gLoSl6kop4cDtERnGROdsIiS++7TMGb51GQlRMgeJuI8e0jOTaY9WNijhDAIZFl4YXysQCCrdqWjJJ7Z14Z/bTv5rWJeBO+zp9qSuphn8OU+YtF7s3COEg96v9kFsL2f6JPqPGFcyEAvQO0S5FayecS2/RtVRjN9wlNAFSfAkBCnXIn1NKOxRIwHM1ZJ2GHXOhQoigVG5iZUE6KafvrzbsXtJS/4VUDGIDlNomg7aMLZSfz9+Dh5KjsOqUkUcdS0n/IDvLHcW8c1ZLQhL3TSzkQBPExx7Fgkn2B/3QYL23b2p+rIxnM75Fxn5GygTW30be/DRYt/GdURxoMEWKh/bgg8MtyY5NDUv3nl38HL/r5Fb5QfiKodyn0vLPH/BiMv+KzxcJGQeDjktF6I+wCAamcab1xFTqGtMNOK8rXNTx3y/IFRVa9D1y+bT4BdCp4k="
